import React from "react";
import Head from "next/head";
import { Map, YMaps } from "@pbe/react-yandex-maps";

export default function index() {
    return (
        <>
            <Head>
                <title>MY SPOT | SPOTS</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta property="og:title" content="MY SPOT" key="title" />
            </Head>
            <YMaps
                enterprise={false}
                version="2.1"
                query={{
                    apikey: "7066165f-a263-468f-9123-b4a3a32bdfb3",
                }}
            >
                <Map
                    width={"100vw"}
                    height={"100vh"}
                    defaultState={{ center: [55.75, 37.57], zoom: 9 }}
                />
            </YMaps>
        </>
    );
}
