"use client";
import React, { useEffect } from "react";
import Head from "next/head";

export default function index() {
    useEffect(() => {
        console.log(document.getElementById("map"));
        ymaps3.ready.then(init);
        const { YMap, YMapDefaultSchemeLayer, YMapControls, YMapListener } =
            ymaps3;
        function init() {
            const map = new YMap(
                document.getElementById("map"),
                {
                    location: {
                        center: [37.64, 55.76],
                        zoom: 14,
                    },
                },
                [new YMapDefaultSchemeLayer()]
            );
        }
    }, []);

    return (
        <>
            <Head>
                <title>MY SPOT | SPOTS</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta property="og:title" content="MY SPOT" key="title" />
            </Head>
            <div id="map" style={{ width: "100vw", height: "100vh" }}></div>
        </>
    );
}
