import Head from "next/head";
import React, { useRef } from "react";
import ReactDOM from "react-dom";
import Image from "next/image";
import images from "constants/images";

const LOCATION = [55.76, 37.64]; // Координаты местоположения на карте
const POINTS = [
    { coordinates: [55.76, 37.64] },
    { coordinates: [55.77, 37.65] },
];

export default function index() {
    React.useEffect(() => {
        window.map = null;
        ymaps3.ready.then(init);
        const map = useRef(null);

        // const {
        //     YMap,
        //     YMapDefaultSchemeLayer,
        //     YMapControls,
        //     YMapDefaultFeaturesLayer,
        //     YMapMarker,
        //     geolocation,
        // } = ymaps3;
        async function init() {
            const [ymaps3React] = await Promise.all([
                ymaps3.import("@yandex/ymaps3-reactify"),
                ymaps3.ready,
            ]);
            const reactify = ymaps3React.reactify.bindTo(React, ReactDOM);

            ///////////////////////////////////////////////////////////////
            var location = geolocation.getPosition();
            var coords;
            location.then(function (res) {
                console.log(res.coords);
                coords = res.coords;
            });
            const { YMapGeolocationControl } = await ymaps3.import(
                "@yandex/ymaps3-controls@0.0.1"
            );
            const { YMapZoomControl } = await ymaps3.import(
                "@yandex/ymaps3-controls@0.0.1"
            );
            map = new YMap(document.getElementById("map"), {
                location: {
                    center: coords === undefined ? [coords] : coords,
                    zoom: 16,
                },
            });
            map.addChild(new YMapDefaultSchemeLayer());
            map.addChild(new YMapDefaultFeaturesLayer());
            map.addChild(
                new YMapControls({ position: "right" }).addChild(
                    new YMapZoomControl({})
                )
            );
            map.addChild(
                new YMapControls({ position: "bottom right" }).addChild(
                    new YMapGeolocationControl({})
                )
            );
            const el = document.createElement("img");
            el.className = "myMarker";
            el.src = "./pin.svg";
            map.addChild(new YMapMarker({ coordinates: [39.72, 47.22] }, el));
        }
        return () => {
            map.current.destroy();
        };
    }, []);
    return (
        <>
            <Head>
                <title>MY SPOT | SPOTS</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta property="og:title" content="MY SPOT" key="title" />
            </Head>
            <div id="map" style={{ width: "100vw", height: "100vh" }}></div>
        </>
    );
}
