"use client";
import Head from "next/head";
import { AnimatePresence, motion } from "framer-motion";
import { useRouter } from "next/router";
import Footer from "../app/layout/footer/footer";
import Header from "../app/layout/header/header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "../scss/index.scss";

export default function App({ Component, pageProps }) {
    const router = useRouter();

    return (
        <>
            <Head>
                <title>MY SPOT</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta property="og:title" content="MY SPOT" key="title" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    type="image/png"
                    sizes="144x144"
                    href="/icon.svg"
                />
                {/* <script src="http://api-maps.yandex.ru/3.0/?apikey=7066165f-a263-468f-9123-b4a3a32bdfb3&lang=ru_RU"></script> */}

                {/* <script src="https://vk.com/js/api/openapi.js?168"></script> */}
                {/* <script type="text/javascript">
                    VK.init( apiId: 7794785 );
                </script> */}
            </Head>
            <Header />
            <AnimatePresence exitBeforeEnter>
                <motion.div
                    key={router.route}
                    initial="initialState"
                    animate="animateState"
                    exit="exitState"
                    transition={{
                        duration: 1,
                    }}
                    variants={{
                        initialState: {
                            zIndex: 10,
                            background: "white",
                            clipPath: "polygon(0 0, 0 0, 0 100%, 0% 100%)",
                        },
                        animateState: {
                            clipPath:
                                "polygon(0 0, 100% 0, 100% 100%, 0% 100%)",
                        },
                        exitState: {
                            clipPath:
                                "polygon(100% 0, 100% 0, 100% 100%, 100% 100%)",
                        },
                    }}
                >
                    <Component {...pageProps} />
                </motion.div>
            </AnimatePresence>
            <ToastContainer
                position="bottom-left"
                autoClose={2000}
                hideProgressBar={true}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="dark"
            />
            <Footer />
        </>
    );
}
