import Head from "next/head";
import DefaultButton from "../app/components/UI/defaultButton/defaultButton";
import Spacer from "../app/components/UI/spacer/spacer";
import { useRouter } from "next/router";

function HomePage() {
    const router = useRouter();
    const handleClick = (e) => {
        e.preventDefault();
        router.push("/signup");
    };
    return (
        <>
            <Head>
                <title>MySpot</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta property="og:title" content="MySpot" key="title" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    type="image/png"
                    sizes="16x16"
                    href="../public/icon.svg"
                />
            </Head>
            <div className="main__wrapper" style={{ height: "100vh" }}>
                <Spacer size={"xl"} />
                <DefaultButton handleClick={handleClick} type={"default"}>
                    THE LUPPA
                </DefaultButton>
            </div>
        </>
    );
}

export default HomePage;
