import styles from "./main.module.scss";
import React from "react";
import Image from "next/image";
import images from "constants/images";
import { useRouter } from "next/router";
import useWindowSize from "Hooks/useWindowSize";
import Head from "next/head";
import { motion } from "framer-motion";

export default function HomePage() {
    // console.log("credentials", data);
    const router = useRouter();
    const handleClick = (e) => {
        e.preventDefault();
        router.push("/map");
    };
    const [x, setXPos] = React.useState(0);
    const [y, setYPos] = React.useState(0);

    const windowSize = useWindowSize();
    let cX = windowSize.width / 2,
        cY = windowSize.height / 2;

    React.useEffect(() => {
        const handleMouse = (e) => {
            setXPos(e.clientX - cX);
            setYPos(e.clientY - cY);
        };
        window.addEventListener("mousemove", handleMouse);
        return () => {
            window.removeEventListener("mousemove", handleMouse);
        };
    }, []);

    const moveBackX = -x / 80 + "px";
    const moveBackY = -y / 80 + "px";
    const moveCenterX = -x / 30 + "px";
    const moveCenterY = -y / 30 + "px";

    return (
        <motion.div className={styles.wrapper}>
            <Head>
                <title>MY SPOT</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta property="og:title" content="MY SPOT" key="title" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    type="image/png"
                    sizes="144x144"
                    href="/icon.svg"
                />
            </Head>
            <div className={styles.wrapper}>
                <div
                    className={styles.backGround}
                    style={{
                        transform: `translate(${moveBackX}, ${moveBackY})`,
                        transformStyle: "preserve-3d",
                    }}
                ></div>
                <div className={styles.main} onClick={handleClick}>
                    <Image
                        src={images.logo}
                        alt="Logo"
                        style={{
                            transform: `translate(${moveCenterX}, ${moveCenterY})`,
                            transformStyle: "preserve-3d",
                        }}
                    />
                </div>
            </div>
        </motion.div>
    );
}

// export async function getServerSideProps() {
//     const res = httpCommon.get("/api/profile.json");
//     const data = await res?.data;
//     return { props: { data } };
// }
