import React from "react";
import TutorialCard from "@/components/TutorialCard/tutorialCard";
import mockCards from "./MockCards";
import styles from "./tutorials.module.scss";
import Spacer from "@/components/UI/spacer/spacer";
import Pagination from "@/components/UI/Pagination/Pagination";
import Head from "next/head";
import Search from "@/components/Search/search";

export default function index() {
    const [tricks, setTricks] = React.useState([]);
    const [fetching, setFetching] = React.useState(false);
    const [currentPage, setCurrentPage] = React.useState(9);

    React.useEffect(() => {
        document.addEventListener("scroll", scrollHandler);
        return function () {
            document.removeEventListener("scroll", scrollHandler);
        };
    }, []);

    const scrollHandler = (e) => {
        if (
            e.target.documentElement.scrollHeight -
                (e.target.documentElement.scrollTop + window.innerHeight) <
            100
        ) {
            setFetching(true);
            setTimeout(() => {
                setFetching(false);
            }, 200);
        }
    };

    React.useEffect(() => {
        if (fetching) {
            setTimeout(() => {
                setCurrentPage((prev) => prev + 9);
            }, 500);
        }
    }, [fetching]);

    return (
        <>
            <Head>
                <title>MY SPOT | TRICKS</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta property="og:title" content="MY SPOT" key="title" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    type="image/png"
                    sizes="144x144"
                    href="/icon.svg"
                />
                <script
                    src="https://api-maps.yandex.ru/3.0/?apikey=7066165f-a263-468f-9123-b4a3a32bdfb3&lang=ru_RU"
                    type="text/javascript"
                ></script>
            </Head>
            <div className="main__height main__wrapper">
                <Spacer size={"xl"} />
                <div className={styles.filter}>
                    <h1>TRICKS —</h1>
                    <Search data={mockCards} placeholder="Search" />
                </div>
                <Spacer size={"md"} />
                <div className={styles.cards}>
                    {mockCards.slice(0, currentPage).map((item) => (
                        <TutorialCard
                            slug={"/"}
                            title={item.title}
                            descr={item.descr}
                            image={item.image}
                        />
                    ))}
                </div>
                {/* <Spacer size={"md"} /> */}
                {/* <Pagination /> */}
                <Spacer size={"xl"} />
            </div>
        </>
    );
}
